
export type Book = {
  id: string;
  slug: string;
  title: string;
  author: string;
  description: string;
  longDescription: string;
  coverImage: string;
  genre: string;
};

export const genres = [
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Horror",
  "Classic Literature",
  "Adventure",
  "Young Adult",
  "Biography",
  "Self-Help"
];

export const books: Book[] = [
  {
    id: "1",
    slug: "dune",
    title: "Dune",
    author: "Frank Herbert",
    description: "A landmark of science fiction, set in the distant future amidst a feudal interstellar society.",
    longDescription: "Dune tells the story of young Paul Atreides, whose family accepts the stewardship of the desert planet Arrakis. As the only source of the valuable substance 'spice', control of Arrakis is a coveted and dangerous undertaking. After a bitter betrayal, Paul must lead a rebellion to restore his family's rightful place.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Science Fiction",
  },
  {
    id: "2",
    slug: "the-hobbit",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy novel about the quest of home-loving Bilbo Baggins to win a share of the treasure.",
    longDescription: "Whisked away from his comfortable, unambitious life in his hobbit-hole in Bag End by the wizard Gandalf and a company of dwarves, Bilbo Baggins finds himself caught up in a plot to raid the treasure hoard of Smaug the Magnificent, a large and very dangerous dragon.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Fantasy",
  },
  {
    id: "3",
    slug: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A classic romance novel that charts the emotional development of the protagonist, Elizabeth Bennet.",
    longDescription: "This classic novel follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich and aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Romance",
  },
  {
    id: "4",
    slug: "to-kill-a-mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A novel about the seriousness of racism and the loss of innocence in the American South.",
    longDescription: "The story, told by the six-year-old Jean Louise Finch, takes place during three years of the Great Depression in the fictional 'tired old town' of Maycomb, Alabama. She and her brother Jem are raised by their widowed father, Atticus Finch, a principled lawyer who defends a black man unjustly accused of a terrible crime.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Historical Fiction",
  },
  {
    id: "5",
    slug: "1984",
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel set in a world of perpetual war, omnipresent government surveillance, and propaganda.",
    longDescription: "The story follows the life of Winston Smith, a low-ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. Winston works in the Ministry of Truth and is driven to rebellion against the totalitarian state.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Science Fiction",
  },
  {
    id: "6",
    slug: "the-great-gatsby",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A novel about the American dream, set in the Jazz Age on Long Island.",
    longDescription: "The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession with the beautiful former debutante Daisy Buchanan. The Great Gatsby explores themes of decadence, idealism, resistance to change, social upheaval, and excess.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Classic Literature",
  },
  {
    id: "7",
    slug: "moby-dick",
    title: "Moby Dick",
    author: "Herman Melville",
    description: "The saga of Captain Ahab and his relentless pursuit of Moby Dick, the great white whale.",
    longDescription: "The book is the sailor Ishmael's narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale that on the ship's previous voyage bit off Ahab's leg at the knee.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Adventure",
  },
  {
    id: "8",
    slug: "the-shining",
    title: "The Shining",
    author: "Stephen King",
    description: "A horror novel about an aspiring writer and recovering alcoholic who accepts a position as the off-season caretaker.",
    longDescription: "Jack Torrance, his wife Wendy, and their young son Danny move into the isolated Overlook Hotel in the Colorado Rockies. As the winter weather cuts them off from the outside world, the hotel's supernatural forces start to influence Jack's sanity, putting his family in terrible danger.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Horror",
  },
  {
    id: "9",
    slug: "the-silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description: "A shocking psychological thriller of a woman’s act of violence against her husband.",
    longDescription: "Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London’s most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Thriller",
  },
  {
    id: "10",
    slug: "and-then-there-were-none",
    title: "And Then There Were None",
    author: "Agatha Christie",
    description: "Ten strangers are lured to an isolated island mansion off the Devon coast by a mysterious host.",
    longDescription: "Ten strangers, each with a secret to hide, are invited to an isolated island. As they settle in, a storm cuts them off from the mainland. One by one, they are picked off, in accordance with the lines of a sinister nursery rhyme. The suspense builds as they realize the killer is one of them.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Mystery",
  },
  {
    id: "11",
    slug: "the-hunger-games",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description: "In a dystopian future, a teenage girl volunteers to take her younger sister's place in a televised fight to the death.",
    longDescription: "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Young Adult",
  },
  {
    id: "12",
    slug: "sapiens-a-brief-history-of-humankind",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "A critically acclaimed book that explores the history of humankind from the Stone Age up to the present day.",
    longDescription: "Professor Yuval Noah Harari's book explores 70,000 years of human history, from the emergence of Homo sapiens to the present. It covers the Cognitive Revolution, the Agricultural Revolution, the unification of humankind, and the Scientific Revolution, offering a unique perspective on our species.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Biography",
  },
  {
    id: "13",
    slug: "the-power-of-now",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "A guide to spiritual enlightenment that encourages living in the present moment.",
    longDescription: "Eckhart Tolle's message is simple: living in the 'now' is the truest path to happiness and enlightenment. The book takes readers on an inspiring spiritual journey to find their true and deepest self and reach the ultimate in personal growth and spirituality: the discovery of truth and light.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Self-Help",
  },
  {
    id: "14",
    slug: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description: "A lone astronaut must save the earth from a disaster in this incredible new science-based thriller.",
    longDescription: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn’t know that. He can’t even remember his own name, let alone the nature of his assignment or how to complete it.",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Science Fiction",
  },
  {
    id: "15",
    slug: "the-midnight-library",
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "A novel about all the choices that go into a life well lived.",
    longDescription: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices . . . Would you have done anything different, if you had the chance to undo your regrets?",
    coverImage: "https://placehold.co/300x450.png",
    genre: "Fantasy",
  }
];
